language: go

go:
    - master

git:
    depth: 1

before_script:
    - go get github.com/lib/pq
    - psql -c 'CREATE DATABASE test_database;' -U postgres
    - psql -c '\i ./sql/extensions.sql' -U postgres -d test_database
    - psql -c '\i ./sql/create_tables.sql' -U postgres -d test_database
    - psql -c '\i ./sql/procedures.sql' -U postgres -d test_database
    - npm install -g sass

      #services:
      #- postgresql

addons:
    postgresql "10.4"
