all: sass_files
	
sass_files:
	sass login.scss login.css
	sass not_logged.scss not_logged.css
	sass login_form.scss login_form.css

clean:
	-rm -rf *.css
	-rm -rf *.css.map
	-rm -rf *~
	-rm -rf .sass-cache
